AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  SlackClientId:
    Description: "Slack App Client ID"
    Type: String
  SlackClientSecret:
    Description: "Slack App Secret Key"
    Type: String
  InstanceSSHKey:
    Description: "SSH key to log into your instance for troubleshooting purposes"
    Type: String
Resources:
  slackappinstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04bf6dcdc9ab498ca
      KeyName: !Ref InstanceSSHKey
      BlockDeviceMappings:
        - DeviceName: "/dev/xvda"
          Ebs:
            VolumeType: "gp2"
            DeleteOnTermination: "true"
            VolumeSize: "10"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -x
          exec > >(tee /var/log/user-data.log|logger -t user-data ) 2>&1
          echo "1. Install nvm"
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
          . ~/.nvm/nvm.sh

          echo "2. Install node.js"
          nvm install node
          node -e "console.log('Running Node.js ' + process.version)"

          echo "3. Install git"
          sudo yum update -y
          sudo yum install git -y
          git version

          echo "4. Download and deploy sample app from git"
          cd /home/ec2-user/
          git clone
          cd aws-quicksight-slackanalytics/webapp
          npm install

          echo "5. Install pm2 and run app"
          npm install pm2 -g
          pm2 --name qs-slackanalytics-app start npm -- start


